### ISSUE TITLE
How to general rotation matrix calculated from ground plane equation？

### ISSUE THREAD

**Issue by lurenlym** [FlorinShum/Rope3D-Toolkit#1]
I am confused about getting the rotation matrix from the ground plane equation
https://github.com/FlorinShum/Rope3D-Toolkit/blob/ff8e634892ad8107159649fce89d28eb1a727f3f/visualize/vis_utils.py#L330

Can you provide more details or give some references to learn? 
Thanks!

**Comment by florinshen** [comment]
The book _Multiple view geometry in computer vision_ is a proper material to learn. For quick understanding,  you can refer to this link https://math.stackexchange.com/questions/432502/finding-the-rotation-angles-of-an-plane, which may help you to understand how to derive a rotation matrix from a ground plane equation.

**Comment by lurenlym** [comment]
> 

Thanks so much!
